// Derive brand.css from the embedded design-system kit: the kit's :root token
// layer plus @font-face rules for its bundled fonts. Run after replacing
// design-system/ with a newer kit. Never edit design-system/ or brand.css by hand.
import { readFileSync, writeFileSync } from "node:fs";
const kit = JSON.parse(readFileSync("design-system/SYSTEM-VERSION.json", "utf8"));
const css = readFileSync("design-system/lleverage.css", "utf8");
const start = css.indexOf(":root{");
const end = css.indexOf("\n}", start) + 2;
const fonts = [
  ["Abhaya Libre", "abhaya-libre-400.woff2", 400], ["Abhaya Libre", "abhaya-libre-500.woff2", 500], ["Abhaya Libre", "abhaya-libre-700.woff2", 700],
  ["Public Sans", "public-sans.woff2", "100 900"], ["Roboto Mono", "roboto-mono.woff2", "100 700"],
];
const faces = fonts.map(([f, file, w]) => `@font-face{font-family:'${f}';src:url('design-system/fonts/${file}') format('woff2');font-weight:${w};font-style:normal;font-display:block;}`).join("\n");
writeFileSync("brand.css", `/* GENERATED by sync-brand.mjs from design-system kit v${kit.version} (tokens ${kit.tokensDigest}). Do not hand-edit. */\n${faces}\n${css.slice(start, end)}\n`);
console.log(`brand.css from kit v${kit.version} (${kit.tokensDigest})`);
